Hw02
Alina-d87/nodejs-homework-2-6 pull request #1
Opened 2022-12-15 06:56 UTC by Alina-d87

2022-12-15 19:59 UTC, BohdanGres requested changes
Привіт, загалом все добре. Трохи накрутила з валідацією. спробуй все провалідувати або Joi або validator. І винеси це в мідлварку

2022-12-16 19:19 UTC, Alina-d87 commented
Добрий вечір! З валідацією розібралась, міделварку зробила. Перевірте будь ласка.

2022-12-17 08:36 UTC, BohdanGres approved these changes
все супер, підчистити контрорллери і можна мержити

2022-12-17 08:36 UTC, BohdanGres commented on controllers/contacts/updateContact.js
> +    const { error } = addSchemasBody.validate(req.body);
тобі це тут вже нетреба, ти зробила цю перевірку в мідлварі

2022-12-17 08:36 UTC, BohdanGres commented on controllers/contacts/addContact.js
> +    const { error } = addSchema.validate(req.body);
тобі це тут вже нетреба, ти зробила цю перевірку в мідлварі

2022-12-17 09:31 UTC, Alina-d87 commented on controllers/contacts/updateContact.js
> +    const { error } = addSchemasBody.validate(req.body);
виправила

2022-12-17 09:31 UTC, Alina-d87 commented on controllers/contacts/addContact.js
> +    const { error } = addSchema.validate(req.body);
виправила

2022-12-17 09:32 UTC, merged